apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskit-notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskit-notification
  template:
    metadata:
      labels:
        app: taskit-notification
    spec:
      containers:
      - name: taskit-notification
        image: gitlab.lnu.se:5050/2dv013/student/gn222gq/part2-architecture/go-notification-service/notification-service
        env:
        - name: AMQP_CONN_STRING
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: TASK_NOTIFICATION_QUEUE_NAME
          value: "task_status_updates"
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: slack-token
        - name: SLACK_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: slack-channel-id
      imagePullSecrets:
      - name: regcred