- name: Deploy MongoDB and Redis to MicroK8s
  hosts: vps
  become: true
  tasks:
    - name: Create database manifests
      copy:
        dest: "/tmp/{{ item }}"
        content: "{{ lookup('template', 'templates/' + item + '.j2') }}"
      loop:
        - mongo-config.yaml
        - redis-config.yaml

    - name: Apply database manifests
      shell: |
        lxc exec {{ control_node_name }} -- microk8s kubectl apply -f /tmp/{{ item }}
      loop:
        - mongo-config.yaml
        - redis-config.yaml