all:
  children:
    vps:
      hosts:
        vps01:
          ansible_host: your.vps.ip # Adjust to your needs
          ansible_user: ubuntu # Adjust to your needs
          ansible_ssh_private_key_file: /path/to/your/private/key.pem # Adjust to your needs