---
- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Remove default nginx conf
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add nginx load balancer template
  template:
    src: ../../../../templates/load-balancer-config.j2
    dest: /etc/nginx/sites-available/load-balancer-config
    owner: root
    group: root
    mode: "0644"

- name: Enable load balancer config
  file:
    src: /etc/nginx/sites-available/load-balancer-config
    dest: /etc/nginx/sites-enabled/load-balancer-config
    state: link

- name: Test Nginx configuration
  command: nginx -t

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
