apiVersion: v1
kind: Service
metadata:
  name: taskit
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30888 
  selector:
    app: taskit-service