---
- name: Enable MicroK8s addons
  shell: |
    microk8s enable dns
    microk8s enable storage
    microk8s enable ingress
    microk8s enable dashboard
    microk8s enable prometheus
    microk8s enable metrics-server
    microk8s enable metallb:{{ metallb_range_start }}-{{ metallb_range_end }}
  become: true

- name: Wait for addons to be ready
  shell: microk8s kubectl wait --for=condition=ready pod -l k8s-app={{ item }} -n kube-system --timeout=300s
  with_items:
    - "kube-dns"
    - "hostpath-provisioner"
    - "nginx-ingress-microk8s"
  become: true

- name: Setup dashboard access
  block:
    - name: Create dashboard admin account
      shell: |
        microk8s kubectl create serviceaccount dashboard-admin -n kube-system
        microk8s kubectl create clusterrolebinding dashboard-admin --clusterrole=cluster-admin --serviceaccount=kube-system:dashboard-admin
      ignore_errors: true

    - name: Generate dashboard token
      shell: microk8s kubectl create token dashboard-admin -n kube-system
      register: dashboard_token

    - name: Save dashboard token
      copy:
        content: "{{ dashboard_token.stdout }}"
        dest: "/var/snap/microk8s/common/credentials/dashboard-token"
        mode: "0600"
  become: true

- name: Generate join command
  shell: microk8s add-node
  register: join_command
  become: true

- name: Save join command for other nodes
  set_fact:
    cluster_join_command: "{{ join_command.stdout_lines[0] }}"
  delegate_to: localhost
  delegate_facts: true
