---
- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
  become: true

- name: Wait for MicroK8s to be ready
  command: microk8s status --wait-ready
  become: true
  retries: 5
  delay: 10

- name: Add user to microk8s group
  user:
    name: ubuntu
    groups: microk8s
    append: yes
  become: true

- name: Create .kube directory
  file:
    path: ~/.kube
    state: directory
    mode: "0755"

- name: Setup kubectl config
  shell: microk8s config > ~/.kube/config
  args:
    creates: ~/.kube/config

- name: Fix kubectl config permissions
  file:
    path: ~/.kube/config
    mode: "0600"
